services:
  web:
    build: .
    volumes:
      - .:/app  # Monta el directorio actual en /app del contenedor
    ports:
      - "8000:8000"  # Expone el puerto 8000
    env_file:
      - .env  # Carga las variables del archivo .env
   

