# Generated by Django 5.1.2 on 2024-10-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('template_id', models.CharField(max_length=100)),
                ('enqueued_time', models.DateTimeField()),
                ('tipo_sensor', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
            ],
        ),
    ]
