# Generated by Django 5.1.2 on 2024-10-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='id_azure',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
