# Generated by Django 5.1.2 on 2024-10-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0002_sensordata_id_azure'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorFisico',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('valor_temperatura', models.FloatField()),
                ('valor_humedad', models.FloatField()),
            ],
        ),
    ]
