# Generated by Django 5.1.2 on 2024-10-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0003_sensorfisico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='enqueued_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
