# Generated by Django 5.1.2 on 2024-10-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0004_alter_sensordata_enqueued_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='enqueued_time',
            field=models.DateTimeField(),
        ),
    ]
