# Generated by Django 5.1.2 on 2024-10-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataExtraction', '0006_alter_sensorfisico_fecha_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorfisico',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
